name: opendata

services:
  judilibre-search:
    build:
      target: local
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/node
