const taxon = {
  4701: "Tribunal de commerce d'Agen",
  1301: "Tribunal de commerce d'Aix-en-Provence",
  2001: "Tribunal de commerce d'Ajaccio",
  8101: "Tribunal de commerce d'Albi",
  6101: "Tribunal de commerce d'Alençon",
  8002: "Tribunal de commerce d'Amiens",
  4901: "Tribunal de commerce d'Angers",
  1601: "Tribunal de commerce d'Angoulême",
  7401: "Tribunal de commerce d'Annecy",
  '0601': "Tribunal de commerce d'Antibes",
  6201: "Tribunal de commerce d'Arras",
  '0702': "Tribunal de commerce d'Aubenas",
  3201: "Tribunal de commerce d'Auch",
  1501: "Tribunal de commerce d'Aurillac",
  8901: "Tribunal de commerce d'Auxerre",
  8401: "Tribunal de commerce d'Avignon",
  5501: 'Tribunal de commerce de Bar-le-Duc',
  9711: 'Tribunal de commerce de Basse-Terre',
  2002: 'Tribunal de commerce de Bastia',
  6401: 'Tribunal de commerce de Bayonne',
  6001: 'Tribunal de commerce de Beauvais',
  9001: 'Tribunal de commerce de Belfort',
  2401: 'Tribunal de commerce de Bergerac',
  2701: 'Tribunal de commerce de Bernay',
  2501: 'Tribunal de commerce de Besançon',
  3402: 'Tribunal de commerce de Béziers',
  4101: 'Tribunal de commerce de Blois',
  9301: 'Tribunal de commerce de Bobigny',
  3302: 'Tribunal de commerce de Bordeaux',
  6202: 'Tribunal de commerce de Boulogne-sur-Mer',
  '0101': 'Tribunal de commerce de Bourg-en-Bresse',
  1801: 'Tribunal de commerce de Bourges',
  2901: 'Tribunal de commerce de Brest',
  5401: 'Tribunal de commerce de Briey',
  1901: 'Tribunal de commerce de Brive-la-Gaillarde',
  1402: 'Tribunal de commerce de Caen',
  4601: 'Tribunal de commerce de Cahors',
  '0602': 'Tribunal de commerce de Cannes',
  1101: 'Tribunal de commerce de Carcassonne',
  8102: 'Tribunal de commerce de Castres',
  9731: 'Tribunal de commerce de Cayenne',
  7102: 'Tribunal de commerce de Chalon-sur-Saône',
  5101: 'Tribunal de commerce de Chalons-en-Champagne',
  7301: 'Tribunal de commerce de Chambéry',
  2801: 'Tribunal de commerce de Chartres',
  3601: 'Tribunal de commerce de Châteauroux',
  5201: 'Tribunal de commerce de Chaumont',
  5001: 'Tribunal de commerce de Cherbourg',
  6303: 'Tribunal de commerce de Clermont-Ferrand',
  9401: 'Tribunal de commerce de Créteil',
  6002: 'Tribunal de commerce de Compiègne',
  5002: 'Tribunal de commerce de Coutances',
  '0301': 'Tribunal de commerce de Cusset',
  4001: 'Tribunal de commerce de Dax',
  7601: 'Tribunal de commerce de Dieppe',
  2104: 'Tribunal de commerce de Dijon',
  5952: 'Tribunal de commerce de Douai',
  8302: 'Tribunal de commerce de Draguignan',
  5902: 'Tribunal de commerce de Dunkerque',
  8801: "Tribunal de commerce d'Épinal",
  2702: "Tribunal de commerce d'Évreux",
  7801: "Tribunal de commerce d'Évry",
  '0901': 'Tribunal de commerce de Foix',
  9721: 'Tribunal de commerce de Fort-de-France',
  8303: 'Tribunal de commerce de Fréjus',
  '0501': 'Tribunal de commerce de Gap',
  '0603': 'Tribunal de commerce de Grasse',
  3801: 'Tribunal de commerce de Grenoble',
  2301: 'Tribunal de commerce de Guéret',
  8501: 'Tribunal de commerce de La Roche-sur-Yon',
  1704: 'Tribunal de commerce de La Rochelle',
  5301: 'Tribunal de commerce de Laval',
  7606: 'Tribunal de commerce du Havre',
  7202: 'Tribunal de commerce du Mans',
  4302: 'Tribunal de commerce du Puy-en-Velay',
  3303: 'Tribunal de commerce de Libourne',
  5910: 'Tribunal de commerce de Lille Métropole',
  8701: 'Tribunal de commerce de Limoges',
  1407: 'Tribunal de commerce de Lisieux',
  3902: 'Tribunal de commerce de Lons-le-Saunier',
  5601: 'Tribunal de commerce de Lorient',
  6901: 'Tribunal de commerce de Lyon',
  7106: 'Tribunal de commerce de Mâcon',
  9761: 'Tribunal de commerce de Mamoudzou',
  '0401': 'Tribunal de commerce de Manosque',
  1303: 'Tribunal de commerce de Marseille',
  7701: 'Tribunal de commerce de Meaux',
  7702: 'Tribunal de commerce de Melun',
  4801: 'Tribunal de commerce de Mende',
  4002: 'Tribunal de commerce de Mont-de-Marsan',
  8201: 'Tribunal de commerce de Montauban',
  '0303': 'Tribunal de commerce de Montluçon',
  3405: 'Tribunal de commerce de Montpellier',
  5402: 'Tribunal de commerce de Nancy',
  9201: 'Tribunal de commerce de Nanterre',
  4401: 'Tribunal de commerce de Nantes',
  1104: 'Tribunal de commerce de Narbonne',
  5802: 'Tribunal de commerce de Nevers',
  '0605': 'Tribunal de commerce de Nice',
  3003: 'Tribunal de commerce de Nîmes',
  4502: "Tribunal de commerce d'Orléans",
  7501: 'Tribunal de commerce de Paris',
  6403: 'Tribunal de commerce de Pau',
  2402: 'Tribunal de commerce de Périgueux',
  6601: 'Tribunal de commerce de Perpignan',
  9712: 'Tribunal de commerce de Pointe-à-Pitre',
  8602: 'Tribunal de commerce de Poitiers',
  7802: 'Tribunal de commerce de Pontoise',
  2903: 'Tribunal de commerce de Quimper',
  5103: 'Tribunal de commerce de Reims',
  3501: 'Tribunal de commerce de Rennes',
  4201: 'Tribunal de commerce de Roanne',
  1203: 'Tribunal de commerce de Rodez',
  2602: 'Tribunal de commerce de Romans',
  7608: 'Tribunal de commerce de Rouen',
  2202: 'Tribunal de commerce de Saint-Brieuc',
  9741: 'Tribunal de commerce de Saint-Denis de La Réunion',
  4202: 'Tribunal de commerce de Saint-Etienne',
  3502: 'Tribunal de commerce de Saint-Malo',
  4402: 'Tribunal de commerce de Saint-Nazaire',
  9742: 'Tribunal de commerce de Saint-Pierre de La Réunion',
  '0202': 'Tribunal de commerce de Saint-Quentin',
  1708: 'Tribunal de commerce de Saintes',
  1304: 'Tribunal de commerce de Salon-de-Provence',
  '0802': 'Tribunal de commerce de Sedan',
  8903: 'Tribunal de commerce de Sens',
  '0203': 'Tribunal de commerce de Soissons',
  1305: 'Tribunal de commerce de Tarascon',
  6502: 'Tribunal de commerce de Tarbes',
  7402: 'Tribunal de commerce de Thonon-les-Bains',
  8305: 'Tribunal de commerce de Toulon',
  3102: 'Tribunal de commerce de Toulouse',
  3701: 'Tribunal de commerce de Tours',
  1001: 'Tribunal de commerce de Troyes',
  5906: 'Tribunal de commerce de Valenciennes',
  5602: 'Tribunal de commerce de Vannes',
  7001: 'Tribunal de commerce de Vesoul - Gray',
  7803: 'Tribunal de commerce de Versailles',
  3802: 'Tribunal de commerce de Vienne',
  6903: 'Tribunal de commerce de Villefranche-sur-Saône - Tarare',
};

module.exports = {
  options: [''].concat(Object.keys(taxon)),
  keys: Object.keys(taxon),
  taxonomy: taxon,
};
