apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${APP_ID}-cert
  namespace: ${APP_GROUP}
spec:
  commonName: ${APP_DNS}
  secretName: ${APP_ID}-cert
  dnsNames:
    - ${APP_DNS}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
