apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: judilibre-elasticsearch
spec:
  version: ${ELASTIC_VERSION}
  nodeSets:
  - name: default
    count: 3
    config:
      xpack.security.enabled: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
          - name: elasticsearch
            readinessProbe:
              httpGet:
                path: /_cluster/health?local=true
                port: 9200
                scheme: HTTP
              initialDelaySeconds: 3
              periodSeconds: 3