apiVersion: v1
clusters:
- name: "${KUBE_NAME}"
  cluster:
    certificate-authority-data: ${KUBE_CA}
    server: ${KUBE_URL}
contexts:
- name: admin@${KUBE_NAME}
  context:
    cluster: "${KUBE_NAME}"
    user: ${KUBE_USER} 
current-context: admin@${KUBE_NAME}
kind: Config
preferences: {}
users:
- name: ${KUBE_USER}
  user:
    token: ${KUBE_TOKEN}
