---
- name: Création du Secret judilibre-search-secret
  kubernetes.core.k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ judilibre_app_id }}-secret"
        namespace: "{{ judilibre_namespace }}"
        labels:
          app: "{{ judilibre_app_id }}"
      type: Opaque
      data:
        HTTP_PASSWD: "{{ HTTP_PASSWORD | b64encode }}"
        ELASTIC_INDEX: "{{ ELASTIC_INDEX | b64encode }}"
        TRANSACTION_INDEX: "{{ TRANSACTION_INDEX | b64encode }}"
        APP_ID: "{{ APP_ID | b64encode }}"
        API_PORT: "{{ API_PORT | b64encode }}"
        ELASTIC_NODE: "{{ ELASTIC_NODE | b64encode }}"
