---
- name: Création du namespace {{ judilibre_search_namespace }}
  kubernetes.core.k8s:
    apply: true
    state: present
    kubeconfig: "{{ kubeconfig_path | default(omit) }}"
    validate_certs: "{{ k8s_validate_certs | default(true) }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ judilibre_search_namespace }}"
