// This list *manually* aggregates various heterogeneous sources,
// some of which provide UPPERCASE or non-accentuated content only.
// This list cannot be produced automatically!
const taxon = [
  'abandon de famille',
  'absence',
  'absence de moyen sommaire',
  'abus de confiance',
  "abus de l'état d'ignorance ou de faiblesse d'une personne",
  'accident de la circulation',
  'accident du travail (loi de 1898)',
  'accident du travail, maladie professionnelle',
  'acquiescement',
  'acte de commerce',
  'acte de notoriété',
  'action civile',
  'action en justice',
  'action oblique',
  'action paulienne',
  'action publique',
  'actions possessoires',
  'adjudication',
  'administrateur provisoire',
  'administration a autrui de substances nuisibles à la sante',
  'administration des domaines',
  'affacturage',
  'affichage',
  'agence de voyages',
  'agent commercial',
  "agent d'affaires",
  "agent d'assurance",
  'agent de police judiciaire',
  'agent immobilier',
  'agressions sexuelles',
  'agriculture',
  'ags',
  'aide judiciaire : contentieux',
  'aide juridictionnelle',
  'aide sociale*',
  'aliments',
  'allocations familiales',
  'alsace lorraine',
  'alsace moselle',
  'amende',
  'amnistie',
  'animaux',
  'apparence',
  'appel - compétence',
  'appel civil',
  'appel correctionnel ou de police',
  'appel en garantie',
  "appellation d'origine",
  'application au droit social des règles du droit commercial',
  'apprentissage et formation professionnelle',
  'arbitrage',
  'arbitrage international',
  'architecte',
  'architecte (honoraires)',
  'architecte entrepreneur',
  'architectes et entrepreneurs',
  'artisan',
  'assedic - chômage',
  'assistance éducative',
  'association',
  'association de malfaiteurs',
  'association syndicale',
  'assurance (règles générales)',
  'assurance caution',
  'assurance construction obligatoire',
  'assurance crédit',
  'assurance de personnes',
  'assurance dommages',
  'assurance maritime',
  'assurance mutuelle',
  'assurance perte de recettes',
  'assurance responsabilité',
  'assurances maritimes',
  'assurances maritimes et transport de marchandises',
  'assurances terrestres',
  'astreinte',
  'astreinte (loi du 9 juillet 1991)',
  'astreinte (législation antérieure à la loi du 9 juillet 1991)',
  "atteinte à l'action de justice",
  "atteinte à l'action de la justice",
  "atteinte à l'autorité de l'état",
  "atteinte à l'intégrité physique ou psychique de la personne",
  'atteinte a la confiance publique',
  'atteinte à la dignité de la personne',
  'atteinte a la vie privée',
  "atteintes au respect de la vie privée et de la présomption d'innocence",
  'attribution préférentielle',
  'autorité de la chose jugée',
  'autorité des marchés financiers',
  'autorité parentale',
  'autorités administratives indépendantes (aai)',
  'autres 1ère chambre civile',
  'autres 2ème chambre civile',
  'autres 3ème chambre civile',
  'autres chambre commerciale',
  'autres chambre sociale',
  'autres droit du travail',
  'autres matières',
  'autres matières (conditions individuelles du salarie)',
  'autres sociale a',
  'autres sociale b',
  'autres sociale c',
  'autres sécurité sociale',
  'avocat',
  'avocat et conseil juridique',
  'avortement',
  'bail (règles générales)',
  'bail a construction',
  'bail a nourriture',
  'bail commercial',
  "bail d'habitation",
  'bail emphytéotique',
  'bail professionnel',
  'bail rural',
  'bail à construction',
  "bail à usage d'habitation et professionnel",
  'banque',
  'banqueroute',
  'blanchiment',
  'bois',
  'bornage',
  'bourse',
  "brevet d'invention",
  "brevet d'invention et connaissances techniques",
  'bruit et tapage',
  "caisse d'épargne",
  'carrière',
  'casier judiciaire',
  'cassation',
  "cause reelle et serieuse - depart de l'entreprise, faute grav",
  'cause réelle et sérieuse - formalités - faute grave',
  'cause réelle et sérieuse - formalités - salaires',
  "cause reelle et serieuse - formalites depart de l'entreprise",
  'cause réelle et sérieuse - formalités salaires faute lourde',
  'cause réelle et sérieuse de licenciement - formalités',
  'cautionnement',
  'cautionnement civil',
  'cautionnement dans la vie des affaires',
  'cession de créance',
  "chambre d'accusation",
  "chambre de l'instruction",
  'chasse',
  'cheque',
  'chômage (indemnisation, chômage partiel)',
  'chose jugée',
  'circulation routière',
  'clauses du contrat de travail (mobilité, non-concurrence, objectifs, variabilité)',
  "comité d'hygiène et sécurité : organisation et fonctionnement",
  'commandement',
  'commandes publiques',
  'commerçant',
  'commissionnaire',
  'communauté européenne',
  'commune',
  'communication audiovisuelle',
  'comparution immédiate',
  'compensation',
  'compétence',
  'complicité',
  'concession immobilière',
  'concubinage et p.a.c.s.',
  'concurrence',
  'concurrence (ordonnance du 1er décembre 1986)',
  'concurrence déloyale ou illicite',
  'concussion',
  'confiscation',
  'conflit collectif du travail',
  'conflit de juridictions',
  'conflit de juridictions (drt soc.)',
  'conflit de lois',
  'conflits collectifs',
  'conflits collectifs du travail (grève / lock-out...)',
  "congés - autres (création d'entreprise, sabbatique)",
  'congés payés',
  'connexité',
  'conseil juridique',
  'construction immobilière',
  'contrainte judiciaire',
  'contrainte par corps',
  "contrat d'entreprise",
  "contrat d'intégration en agriculture",
  'contrat de travail',
  'contrat de travail à durée déterminée',
  'contrat de travail et mandat social',
  'contrat de travail, durée déterminée',
  'contrat de travail, exécution',
  'contrat de travail, formation',
  "contrat de travail, période d'essai",
  'contrat de travail, rupture',
  'contrat de travaux',
  'contrat judiciaire',
  'contrat nouvelles embauches',
  'contrats aidés',
  'contrats commerciaux',
  "contrats commerciaux lorsqu'une partie non commerçante a choisi la voie civile",
  'contrats de distribution',
  'contrats et obligations civils',
  'contrats et obligations conventionnelles',
  'contrats à durée déterminée',
  'contravention',
  'contrefaçon',
  "contrôle d'identité",
  'contrôle judiciaire',
  'contumace',
  "convention européenne des droits de l'homme",
  "convention européenne de sauvegarde des droits de l'homme et des libertés",
  'conventions collectives',
  'conventions collectives : application',
  'conventions et accords collectifs : interprétation et application',
  'conventions et accords collectifs : négociation et régime',
  'conventions internationales',
  'coopérative agricole',
  'copropriété',
  'corruption',
  'corse',
  'coups et violences volontaires',
  "cour d'assises",
  'cour de justice de la république',
  'cours et tribunaux',
  'courses de chevaux',
  'courtier',
  "crime contre l'humanité",
  "crimes et délits commis à l'étranger",
  'crimes et delits commis par des magistrats et certains fonctionnaires',
  'crimes et délits flagrants',
  'crédit-bail',
  'crédit-bail immobilier',
  'cultes',
  "cumul idéal d'infractions",
  'déchéance',
  'délais',
  'délégation de créance',
  'démarchage',
  'dénonciation calomnieuse',
  'dénonciation téméraire ou abusive',
  'départ de l’entreprise (certificat travail, etc.)',
  "départ de l'entreprise (certif. de travail, non concurr., etc.)",
  "départ de l'entreprise - salaire",
  'département',
  'dépôt',
  'dessins et modèles',
  'destructions, dégradations et détériorations',
  'détention provisoire',
  "détournement d'objets saisis ou remis en gage",
  "détournement de gage ou d'objet saisi",
  'détournement par dépositaire public',
  'diffamation et injures',
  'diffamations et injures',
  'discipline des avocats, officiers minist., conseils juridiques',
  'discrimination',
  'discrimination syndicale',
  'divorce, séparation de corps',
  'domaine',
  'domicile',
  'donation',
  'donation-partage',
  'donations',
  'douanes',
  'droit civil',
  'droit commercial (application au droit social du...) et procédures collectives',
  'droit commercial communautaire',
  'droit commercial et procédures collectives',
  "droit d'habitation",
  'droit de la concurrence',
  'droit de la négociation collective',
  'droit de rétention',
  'droit des assurances',
  'droit des sociétés',
  "droit disciplinaire (règlement intérieur de l'entreprise/amnistie)",
  'droit du travail',
  'droit européen',
  'droit fiscal',
  'droit international privé',
  'droit international privé (drt soc.)',
  'droit international privé - déplacement illicite',
  'droit local',
  'droit maritime',
  'droit maritime du travail - marins',
  'droit public - droit administratif',
  'droit syndical',
  'droits de la personnalité',
  'durée du travail : lois Aubry (ou lois sur les 35 heures)',
  'durée et temps de travail (astreintes/travail effectif/repos hebdomadaire...)',
  "départ de l'entreprise : certificat de travail, reçu pour solde de tout compte",
  'dépôt',
  'eaux',
  'échange',
  'effet de commerce',
  'élections',
  "élections aux chambres d'agriculture (inscription sur les listes)",
  "élections aux chambres d'agriculture (régularité des élections)",
  "élections aux chambres de commerce et d'industrie (inscription sur les listes)",
  "élections aux chambres de commerce et d'industrie (régularité des élections)",
  'élections aux chambres des métiers (inscription sur les listes)',
  'élections aux chambres des métiers (régularité des élections)',
  "élections aux conseils consultatifs des caisses d'épargne et de prévoyance (inscription sur les listes)",
  "élections aux conseils consultatifs des caisses d'épargne et de prévoyance (régularité des élections)",
  'élections aux conseils de la mutualité sociale agricole (inscription sur les listes)',
  'élections aux conseils de la mutualité sociale agricole (régularité des élections)',
  "élections aux conseils de prud'homme (inscription sur les listes)",
  "élections aux conseils de prud'homme (régularité des élections)",
  'élections aux ophlm (inscription sur les listes)',
  'élections aux ophlm (régularité des élections)',
  'élections aux tribunaux de commerce (inscription sur les listes)',
  'élections aux tribunaux de commerce (régularité des inscriptions)',
  'élections aux unions régionales des médecins exerçant à titre libéral (inscription sur les listes)',
  'élections aux unions régionales des médecins exerçant à titre libéral (régularité des élections)',
  'élections forestières (inscription sur les listes)',
  'élections forestières (régularité des élections)',
  'élections professionnelles',
  'élections sociales',
  'élections sécurité sociale (inscription sur les listes)',
  'élections sécurité sociale (régularité des élections)',
  'élections, organismes divers',
  'emploi',
  'empoisonnement',
  'énergie',
  'enlèvement et séquestration',
  'enquête préliminaire',
  'enquêteur social',
  'enseignement',
  'entrave à la liberté des enchères',
  'entrepreneurs : responsabilité',
  'entreprise en difficulté (loi du 26 juillet 2005)',
  'entreprise en difficulté (prévention et règlement amiable)',
  'entreprise en difficulté',
  'entreprise en difficulté (loi du 1er mars 1984)',
  'entreprise en difficulté (loi du 25 janvier 1985)',
  'entreprise en difficulté - responsabilité et sanctions',
  'entreprise à statut spécial : edf, ratp, sncf, air france...',
  'entreprises de presse',
  'environnement et pollution',
  'erreur',
  'escroquerie',
  'essai (contrat de travail...)',
  'état',
  'état civil',
  'état de santé (maladie, accident, maternité)',
  'etat de santé - accident du travail et maladie professionnelle',
  'état de santé - accident et maladie non professionnelle',
  'état de santé - maternité',
  'état de santé - règles communes',
  'étranger',
  'évasion',
  'excitation de mineurs à la débauche',
  'exécution provisoire',
  'exequatur',
  'existence du contrat de travail',
  'existence du contrat de travail (sauf c2)',
  'expatriés - travailleurs détachés',
  'expert judiciaire',
  'expert judiciaire (discipline)',
  'expert judiciaire (inscription)',
  'expert-comptable et comptable agréé',
  'exploits',
  'expropriation',
  'expropriation (arrêt)',
  "expropriation pour cause d'utilité publique",
  'extorsion',
  'extradition',
  'faillite, regl judiciaire, liqui biens suspens poursuites',
  'faits justificatifs',
  "faute grave - faute lourde - départ de l'entreprise",
  'faute grave - faute lourde - salaire',
  'faute grave - faute lourde en droit du travail',
  'faux',
  'fiançailles',
  'fichier national automatise des empreintes génétiques',
  'fichiers et libertés publiques',
  'filiation',
  'fonctionnaires et agents publics',
  'fondation',
  'fonds de commerce',
  'fonds de garantie',
  'foret',
  'forfaits en jours/heures, forfaits de rémunération',
  'formation professionnelle',
  'frais et dépens',
  'frais professionnels',
  'fraude',
  'fraudes et falsifications',
  'garde à vue',
  'grâce',
  'greffier',
  "groupement d'intérêt économique",
  'habitation à loyer modéré',
  'handicapé',
  'harcèlement',
  'haute cour de justice',
  'homicide et blessures involontaires',
  'homicide volontaire',
  "honoraires d'avocat",
  'hôpital',
  'hôtelier',
  'hygiène et sécurité',
  'hypothèque',
  'hypothèque provisoire judiciaire',
  'immeuble',
  'immunité',
  'impôts et taxes',
  'imputabilité rupture contrat travail à durée indéterminée',
  'imputabilité de la rupture du contrat de travail',
  'impôts et taxes',
  'incapacités',
  'indemnisation des dégâts causés par le gibier',
  "indemnisation des victimes d'attentat",
  "indemnisation des victimes d'attentat terroriste",
  "indemnisation des victimes d'infraction",
  'indivisibilité',
  'indivision',
  'informatique',
  'ingérence des fonctionnaires',
  'injonction de faire',
  'injonction de payer',
  'injures',
  'inscription de faux',
  'insolvabilité frauduleuse',
  'institutions représentatives',
  'institutions représentatives des salaries',
  "institutions représentatives du personnel (comité d'entreprise/délégué du personnel...)",
  'instruction',
  'interdiction de séjour',
  'interdiction des droits civiques, civils et de famille',
  'intérêts',
  'interprète',
  'intervention',
  'irrecevabilité',
  'irrecevabilités et déchéances',
  'ivresse',
  'jeux de hasard',
  'journalistes/pigistes',
  'juge aux affaires familiales',
  "juge de l'exécution",
  'juge des libertés et de la détention',
  'jugements et arrêts',
  'jugements et arrêts avant dire droit',
  'jugements et arrêts par défaut',
  'juridictions',
  'juridictions correctionnelles',
  'justice militaire',
  'légitime défense',
  "lettre d'intention",
  'libération conditionnelle',
  'liberté de la presse',
  "liberté du commerce et de l'industrie",
  'libéralités',
  'licenciement cause réelle et sérieuse faute grave...',
  'licenciement disciplinaire (pour faute)',
  'licenciement personnel non disciplinaires',
  'licenciement pour motif économique',
  'licenciement économique collectif',
  'licenciement économique individuel',
  'licenciements soumis à autorisation',
  'liquidations',
  'location financière',
  'location-attribution',
  'location-vente',
  'lois et règlements',
  'lotissement',
  "législation d'outre-mer",
  'magistrat',
  'maire',
  'majeur protégé',
  'maladie - maternité',
  'maladie, maternité, service national',
  'mandat',
  "mandat d'arrêt européen",
  "mandat d'intérêt général",
  'mandat entre commerçants',
  'manifestation sur la voie publique (decret du 23 octobre 1935)',
  'marche public*',
  'mariage',
  'marque de fabrique',
  "maternité (congé de maternité, parental d'éducation)",
  'menaces',
  "mesures d'instruction",
  'meuble',
  'mines',
  'mineur',
  'ministère public',
  'mise en danger de la personne',
  'mitoyenneté',
  'modification de la situation juridique de l’entreprise',
  "modification de la situation juridique de l'employeur",
  "modification de la situation juridique de l'employeur (l.1224-1 du code du travail)",
  'modification du contrat de travail',
  'modification du contrat de travail pour motif économique (l.1222-6 du code du travail)',
  'monnaie',
  'monuments historiques',
  'mutualité',
  'mutualité sociale agricole',
  'médiateur judiciaire',
  'médiateurs (inscription)',
  'nantissement',
  'nationalisation',
  'nationalité',
  'navigation aérienne',
  'navigation de plaisance',
  'navigation fluviale',
  'navigation maritime',
  'négociations des conventions et accords collectifs',
  'nom',
  'nom commercial',
  "non-représentation d'enfant",
  'novation',
  'objets mobiliers (dommages causes par)',
  'obligation alimentaire',
  'obligation naturelle',
  'officier de police judiciaire',
  'officiers publics ou ministériels',
  'omission de porter secours',
  'ordonnances sur requête et référé',
  'ordre entre créanciers',
  'ordre et contribution',
  'ordres professionnels et professions organisées',
  'organismes internationaux',
  'outre-mer',
  'pacte civil de solidarité et concubinage',
  'pacte sur succession future',
  'paiement',
  'paiement direct des pensions',
  'partage',
  'participation des salariés (intéressement)',
  'pêche',
  'pêche fluviale',
  'pêche maritime',
  'peines',
  'personne morale',
  'pollution',
  'pompes funèbres',
  'portage salarial',
  'porte-fort',
  'possession',
  'postes et communications électroniques',
  'pouvoir disciplinaire - règlement intérieur',
  "pouvoir disciplinaire du chef d'entreprise",
  'pouvoirs des juges',
  'pouvoirs du premier président',
  'pratiques restrictives de concurrence',
  'prescription',
  'prescription acquisitive',
  'prescription civile',
  'presse',
  'prêt',
  'preuve',
  'preuve des obligations',
  'prise à partie',
  'privilèges',
  'privilèges immobiliers',
  'procédure alsace lorraine',
  'procédure civile',
  'procédure civile et commerciale',
  'procédure civile et sociale',
  "procédure prud'homale, procédure civile",
  "procédures civiles d'exécution",
  'procédures de distribution',
  'procès-verbal',
  'procédure civile',
  "procédure prud'homale",
  "procédures civiles d'exécution",
  'professions (en général)',
  'professions commerciales',
  'professions médicales et paramédicales',
  'promoteurs : responsabilité',
  'propriété',
  'propriété industrielle (brevets, marques, dessins)',
  'propriété littéraire et artistique',
  'propriété immobilière',
  'propriété industrielle',
  'propriété littéraire et artistique',
  "protection de la nature et de l'environnement",
  'protection des consommateurs',
  'protection des droits de la personne',
  'provocation au suicide',
  'proxénétisme',
  "prud'hommes",
  'prêt',
  'publicité',
  'publicité commerciale',
  'publicité foncière',
  'pupilles de la nation',
  'quasi-contrat',
  'questions préjudicielles',
  'rapatrié',
  'rébellion',
  'recel',
  'récidive',
  'recours en révision',
  'récusation',
  'redressement judiciaire',
  'réexamen',
  'référé',
  'régimes matrimoniaux',
  'registre du commerce et des sociétés',
  'règlement de juges',
  "règlement intérieur de l'entreprise",
  'règlementation du travail (duree, jours feries, repos hebdo)',
  'règlementation économique',
  'réhabilitation',
  'relèvement des interdictions, déchéances ou incapacités',
  'remembrement rural',
  'remembrement urbain',
  'renonciation',
  'rente viagère',
  "renvoi d'un tribunal a un autre",
  "réparation a raison d'une détention",
  'représentation des salariés',
  "requête en rectification d'erreurs matérielles",
  'responsabilité civile',
  'responsabilité contractuelle',
  'responsabilité délictuelle ou quasi délictuelle',
  'responsabilité du fait des produits défectueux',
  'responsabilite medicale (medecins, chirurgiens, chir-dentistes)',
  'responsabilité pénale',
  'responsabilité contractuelle',
  'responsabilité du fait des animaux',
  "responsabilité du prestataire de services d'investissement",
  'responsabilité délictuelle ou quasi délictuelle',
  'responsabilité du fait des produits défectueux',
  'restitution',
  'rétention des étrangers (art. 35 ordonnance du 2 nov. 45)',
  'retraites',
  'revendication immobilière',
  'révision',
  'rupture du contrat de travail (démission, retraite…)',
  "rupture négociée du contrat de travail (transaction et rupture d'un commun accord)",
  'règlement judiciaire liquidation des biens (loi du 13 juillet 1967)',
  "référé prud'homal",
  'régimes matrimoniaux',
  "réglementation du travail (non recensée sous d'autres rubriques spécifiques)",
  'rémunération (salaires et accessoires)',
  's.a.f.e.r.',
  'saisie immobilière',
  'saisies',
  'saisies (législation antérieure à la loi du 9 juillet 1991)',
  'salaires et accessoires',
  'salariés à statut particulier (vrp, apprentis artistes, etc.)',
  'salariés à statut particulier (artistes, assistantes maternelles, employés de maison, journalistes, gérants non salariés, dockers...)',
  'sante publique',
  'sauvegarde des entreprises',
  'scelles',
  'secret professionnel',
  'sécurité sociale',
  'sécurité sociale, accident du travail',
  'securite sociale, allocation vieillesse pour personnes non salariees',
  'sécurité sociale, allocations diverses',
  'securite sociale, assurance des non-salaries (loi du 12 juillet 1966)',
  'sécurité sociale, assurances sociales',
  'sécurité sociale, contentieux',
  'sécurité sociale, prestations familiales',
  'sécurité sociale, régimes complémentaires',
  'sécurité sociale, régimes spéciaux',
  'séparation des pouvoirs',
  'sépulture',
  'séquestre',
  'service national',
  'servitude',
  'simulation',
  'smic',
  'société',
  'société (règles générales)',
  'société à capital variable',
  'société à responsabilité limitée',
  'société anonyme',
  'société civile',
  'société civile immobilière',
  'société civile professionnelle',
  'société commerciale (règles générales)',
  'société coopérative',
  'société créée de fait',
  "société d'aménagement foncier et d'établissement rural",
  "société d'économie mixte",
  "société d'exercice libéral",
  "société d'intérêt collectif agricole",
  "société d'investissement",
  'société de capitalisation',
  'société de caution mutuelle',
  'société de crédit différé',
  'société de fait',
  'société en commandite',
  'société en nom collectif',
  'société en participation',
  'société étrangère',
  'société européenne',
  'société par actions simplifiée',
  'société civile',
  'société civile immobilière',
  'société civile professionnelle',
  'société commerciale',
  'sociétés',
  'sociétés coopératives ouvrières de production (s.c.o.(o.)p.)',
  'solidarité',
  'spectacles',
  'sports',
  "sports-aviation (contrats de travail conclus dans les sports et l'aviation)",
  'statut collectif du travail',
  'statut des salariés protégés',
  'statuts professionnels particuliers',
  'stipulation pour autrui',
  'subornation de témoins',
  'subrogation',
  'substances vénéneuses',
  'substitution permise',
  'substitution prohibée',
  'succession',
  'surendettement des particuliers et des familles',
  'suretés réelles immobilières',
  'suspicion légitime',
  'syndicat',
  'syndicat professionnel',
  'sécurité sociale',
  'sécurité sociale, accident du travail',
  'sécurité sociale, aide sociale',
  'sécurité sociale, allocation vieillesse pour personnes non-salariées',
  'sécurité sociale, assurances sociales des travailleurs indépendants des professions non-agricoles',
  'sécurité sociale, assurances sociales du régime général',
  'sécurité sociale, contentieux',
  'sécurité sociale, cotisations et contributions du régime général',
  'sécurité sociale, prestations familiales',
  'sécurité sociale, régimes complémentaires',
  'sécurité sociale, régimes spéciaux et régimes divers',
  'séparation de corps',
  'séparation des pouvoirs',
  'sépulture',
  'séquestre',
  'tabac',
  'tarifs des officiers publics ou ministériel et avocats postulants',
  'taux du ressort',
  'techniciens du bâtiment : responsabilité',
  'temps partiel/travail intermittent',
  'tentative',
  'terrorisme',
  'testament',
  'tierce opposition',
  'titre nobiliaire',
  'tourisme',
  'transaction',
  'transport de marchandises',
  'transport de personnes',
  'transports aériens',
  'transports en commun',
  'transports ferroviaires',
  'transports fluviaux',
  'transports maritimes',
  'transports routiers',
  'transports routiers/ambulances',
  'travail intérimaire',
  "travail reglementation, contrôle de l'application de la legislation",
  'travail réglementation, durée du travail',
  'travail réglementation, rémunération',
  'travail réglementation, sante et sécurité',
  'travail réglementation (travail dissimulé et des étrangers...)',
  'travail temporaire',
  'trésor public',
  "tribunal d'instance",
  'tribunal de commerce',
  'tribunal de police',
  'trouble de voisinage',
  'troubles de voisinage en matière de construction',
  'union européenne',
  'urbanisme',
  'usages',
  'usages et engagements unilatéraux',
  'usufruit',
  'usure',
  "usurpation d'état civil",
  'usurpation de titre ou fonction',
  'v.r.p.',
  'vente',
  'vente commerciale',
  'vente immobilière',
  'vente mobilière',
  "vérification d'écriture",
  'vie personnelle du salarié et libertés individuelles et collectives',
  'vins',
  'viol',
  'violation de domicile',
  'visite et saisie domiciliaires',
  "voies d'exécution",
  'voirie',
  'vol',
];

module.exports = {
  options: taxon,
  keys: null,
  taxonomy: taxon,
};
