const source = {
  ABSEN: 'Absence',
  ACCIR: 'Accident de la circulation',
  ACPOS: 'Actions possessoires',
  ACTRA: 'Sécurité sociale, accident du travail',
  ADJUD: 'Adjudication',
  AGIMM: 'Agent immobilier',
  AIJUD: 'AIDE JUDICIAIRE : CONTENTIEUX',
  ALLOC: 'ALLOCATIONS FAMILIALES',
  ANIMA: 'Responsabilité du fait des animaux',
  ARBIN: 'Arbitrage international',
  ARBIT: 'Arbitrage',
  ARCHI: 'Architectes et entrepreneurs',
  ARHON: 'Architecte (honoraires)',
  ASEDU: 'Assistance éducative',
  ASMAR: 'Assurances maritimes',
  ASSOC: 'Association',
  ASTER: 'Assurances terrestres',
  ASTRE: 'Astreinte',
  ATPRE: 'ATTRIBUTION PREFERENTIELLE',
  AUCHO: 'AUTORITE DE LA CHOSE JUGEE',
  AUPAR: 'Autorité parentale',
  AUTAO: 'AUTRES MATIERES',
  AUTAR: 'AUTRES MATIERES',
  AUTBO: 'AUTRES MATIERES (CONDITIONS INDIVIDUELLES DU SALARIE)',
  AUTBR: 'AUTRES MATIERES (CONDITIONS INDIVIDUELLES DU SALARIE)',
  AUTC1: 'Autres 1ère chambre civile',
  AUTC2: 'Autres 2ème chambre civile',
  AUTC3: 'Autres 3ème chambre civile',
  AUTCO: 'Autres chambre commerciale',
  AUTSA: 'AUTRES SOCIALE A',
  AUTSB: 'AUTRES SOCIALE B',
  AUTSC: 'AUTRES SOCIALE C',
  BAHAB: "Bail à usage d'habitation et professionnel",
  BANQU: 'Banque',
  BARUR: 'Bail rural',
  BORNA: 'Bornage',
  BOURS: 'Bourse',
  CACOM: 'Cautionnement dans la vie des affaires',
  CHASS: 'Indemnisation des dégâts causés par le gibier',
  CHOMO: 'CHOMAGE ( INDEMNISATION, CHOMAGE PARTIEL )',
  CHOMR: 'CHOMAGE (INDEMNISATION, CHOMAGE PARTIEL)',
  COCIV: 'Contrats et obligations civils',
  COCM1: 'Contrats commerciaux',
  COCM2: "Contrats commerciaux lorsqu'une partie non commerçante a choisi la voie civile",
  COCOO: 'CONVENTIONS COLLECTIVES : APPLICATION',
  COCOR: 'CONVENTIONS COLLECTIVES : APPLICATION',
  COENT: "Contrat d'entreprise",
  COINT: "Contrat d'intégration en agriculture",
  CONCO: 'Conflit collectif du travail',
  CONCR: 'CONFLITS COLLECTIFS',
  CONCU: 'Concurrence',
  CONFA: 'CONTREFACON',
  CONFL: 'Conflit de juridictions',
  CONST: 'Construction immobilière',
  CONTR: 'CONTRIB CHARGES MARIAGE SF DIVORCE SEPARATION DE CORPS',
  CONVE: 'CONVENTIONS COLLECTIVES',
  COOPE: 'Coopérative agricole',
  COPRO: 'Copropriété',
  COTDO: 'Contrat de travail, durée déterminée',
  COTDR: "CONTRAT DE TRAVAIL,  PERIODE D'ESSAI",
  COTEO: 'EXISTENCE DU CONTRAT DE TRAVAIL',
  COTER: 'EXISTENCE DU CONTRAT DE TRAVAIL',
  COTR1: 'CONTRAT DE TRAVAUX',
  COTR2: 'CONTRAT DE TRAVAIL',
  COTR3: 'EXISTENCE DU CONTRAT DE TRAVAIL (SAUF C2)',
  COTR4: 'CONTRAT DE TRAVAIL A DUREE DETERMINEE',
  COTR5: 'IMPUTABILITE RUPTURE CONTRAT TRAVAIL A DUREE INDETERMINEE',
  COTRO: 'RUPTURE DU CONTRAT DE TRAVAIL MODIFDEMISSION RETRAITE...',
  COTRR: 'RUPTURE DU CONTRAT DE TRAVAIL MODIFDEMISSION RETRAITE ..',
  CREDI: 'Crédit-bail',
  CRSDE: "CAUSE REELLE ET SERIEUSE - FORMALITES DEPART DE L'ENTREPRISE",
  CRSDG: "CAUSE REELLE ET SERIEUSE - DEPART DE L'ENTREPRISE,FAUTE GRAV",
  CRSGR: 'CAUSE REELLE ET SERIEUSE - FORMALITES - FAUTE GRAVE',
  CRSLO: 'CAUSE REELLE ET SERIEUSE - FORMALITES SALAIRES FAUTE LOURDE',
  CRSSA: 'CAUSE REELLE ET SERIEUSE - FORMALITES - SALAIRES',
  DCDSO: 'APPLICATION AU DROIT SOCIAL DES REGLES DU DROIT COMMERCIAL',
  DCDSR: 'DROIT COMMERCIAL ET PROCEDURES COLLECTIVES',
  DECSO: 'DECHEANCE',
  DECSR: 'DECHEANCE',
  DEPAO: 'DEPART DE L ENTREPRIS(CERTIFICAT TRAVAIL ETC)',
  DEPAR: "DEPART DE L'ENTREPRISE (CERTIF.DE TRAVAIL,NON CONCURR...ETC)",
  DEPOT: 'Dépôt',
  DEPSA: "DEPART DE L'ENTREPRISE - SALAIRE",
  DIFFA: 'Diffamations et injures',
  DISCI: 'DISCIPLINE DES AVOCATS,OFFICIERS MINIST.,CONSEILS JURIDIQUES',
  DIVOR: 'Divorce, séparation de corps',
  DOMIC: 'Domicile',
  DOUAN: 'Douanes',
  DRASS: 'DROIT DES ASSURANCES',
  DRCCO: 'Droit commercial communautaire',
  DRCON: 'DROIT DE LA CONCURRENCE',
  DRFIS: 'DROIT FISCAL',
  DRINT: 'Droit international privé',
  DRMAR: 'Droit maritime',
  DRPER: 'DROITS DE LA PERSONNALITE',
  DRSOC: 'DROIT DES SOCIETES',
  DRTRA: 'Droit du travail',
  EFCOM: 'Effet de commerce',
  ELECT: 'Elections',
  ENTD1: 'Entreprise en difficulté (loi du 1er mars 1984)',
  ENTPR: 'ENTREPRISES DE PRESSE',
  ENTRE: 'ENTREPRENEURS : RESPONSABILITE',
  EPROF: 'Elections sociales',
  ETATC: 'Etat civil',
  EXEQU: 'EXEQUATUR',
  EXPER: 'Expert judiciaire (discipline)',
  EXPRO: 'Expropriation',
  FAILL: 'FAILLITE, REGL JUDICIAIRE, LIQUI BIENS SUSPENS POURSUITES',
  FAUTE: 'FAUTE GRAVE - FAUTE LOURDE EN DROIT DU TRAVAIL',
  FAUX: 'Faux',
  FGLDE: "FAUTE GRAVE - FAUTE LOURDE - DEPART DE L'ENTREPRISE",
  FGLSA: 'FAUTE GRAVE - FAUTE LOURDE - SALAIRE',
  FILIA: 'Filiation',
  FONCT: 'Fonctionnaires et agents publics',
  FONDA: 'Fondation',
  FONDS: 'Fonds de commerce',
  FRAIS: 'Frais et dépens',
  HONOR: "Honoraires d'avocat",
  HYPOT: 'Hypothèque',
  HYPRO: 'Hypothèque provisoire judiciaire',
  INCAP: 'Incapacités',
  INDEM: "Indemnisation des victimes d'infraction",
  INDIV: 'Indivision',
  INSTI: 'INSTITUTIONS REPRESENTATIVES DES SALARIES',
  INSTO: 'INSTITUTIONS REPRESENTATIVES',
  INSTR: 'INSTITUTIONS REPRESENTATIVES',
  LIBER: 'Libéralités',
  LICAO: 'LICENCIEMENTS SOUMIS A AUTORISATION',
  LICAR: 'LICENCIEMENTS SOUMIS A AUTORISATION',
  LICAU: 'LICENCIEMENTS SOUMIS A AUTORISATION',
  LICEN: 'CAUSE REELLE ET SERIEUSE DE LICENCIEMENT - FORMALITES',
  LICEO: 'LICENCIEMENT CAUSE REELLE ET SERIEUSE FAUTE GRAVE...',
  LICER: 'LICENCIEMENT CAUSE REELLE ET SERIEUSE FAUTE GRAVE ...',
  LIECO: 'LICENCIEMENT POUR MOTIF ECONOMIQUE',
  LIECR: 'LICENCIEMENT POUR MOTIF ECONOMIQUE',
  LIPRE: 'LIBERTE DE LA PRESSE',
  LIQUI: 'LIQUIDATIONS',
  LOTIS: 'Lotissement',
  MALAD: 'MALADIE - MATERNITE',
  MALAO: 'MALADIE, MATERNITE, SERVICE NATIONAL',
  MALAR: 'MALADIE, MATERNITE, SERVICE NATIONAL',
  MANDA: 'Mandat',
  MAPRO: 'ACCIDENT DU TRAVAIL, MALADIE PROFESSIONNELLE',
  MAPRR: 'ACCIDENT DU TRAVAIL, MALADIE PROFESSIONNELLE',
  MARIA: 'Mariage',
  MITOY: 'MITOYENNETE',
  NATIO: 'Nationalité',
  NEGOC: 'DROIT DE LA NEGOCIATION COLLECTIVE',
  NEGOO: 'NEGOCIATIONS DES CONVENTIONS ET ACCORDS COLLECTIFS',
  NEGOR: 'NEGOCIATIONS DES CONVENTIONS ET ACCORDS COLLECTIFS',
  NOMPA: 'Nom',
  OBALI: 'Obligation alimentaire',
  OBJET: 'OBJETS MOBILIERS (DOMMAGES CAUSES PAR)',
  ORCON: 'Ordre et contribution',
  ORDRE: 'Ordres professionnels et professions organisées',
  PAIDI: 'PAIEMENT DIRECT DES PENSIONS',
  PARTA: 'Partage',
  PLAIS: 'Navigation de plaisance',
  PRALS: 'PROCEDURE ALSACE LORRAINE',
  PRCIV: 'Procédure civile',
  PRCOM: 'PROCEDURE CIVILE ET COMMERCIALE',
  PREOB: 'Preuve des obligations',
  PRET: 'Prêt',
  PRIMM: 'Propriété immobilière',
  PRIND: 'PROPRIETE INDUSTRIELLE (BREVETS, MARQUES, DESSINS)',
  PRISE: 'Prise à partie',
  PRIVI: 'PRIVILEGES IMMOBILIERS',
  PRLIT: 'Propriété littéraire et artistique',
  PROCO: 'Protection des consommateurs',
  PROFE: 'PROFESSIONS COMMERCIALES',
  PROMO: 'PROMOTEURS : RESPONSABILITE',
  PRSOC: 'PROCEDURE CIVILE ET SOCIALE',
  PRSOO: "PROCEDURE PRUD'HOMALE, PROCEDURE CIVILE",
  PRSOR: "PROCEDURE PRUD'HOMALE, PROCEDURE CIVILE",
  PUBLI: 'Publicité foncière',
  PUPIL: 'Pupilles de la nation',
  PVDIO: 'POUVOIR DISCIPLINAIRE - REGLEMENT INTERIEUR',
  PVDIR: 'POUVOIR DISCIPLINAIRE - REGLEMENT INTERIEUR',
  PVDIS: "POUVOIR DISCIPLINAIRE DU CHEF D'ENTREPRISE",
  RAPAT: 'Rapatrié',
  REDRE: 'REDRESSEMENT JUDICIAIRE',
  REGIM: 'Régimes matrimoniaux',
  REGIN: "REGLEMENT INTERIEUR DE L'ENTREPRISE",
  REGLI: 'Règlement judiciaire liquidation des biens (Loi du 13 juillet 1967)',
  REMEM: 'Remembrement rural',
  RENTE: 'Rente viagère',
  RETEN: 'RETENTION DES ETRANGERS (ART. 35 ORDONNANCE DU 2 NOV. 45)',
  RETRO: 'REGLEMENTATION DU TRAVAIL (DUREE,JOURS FERIES, REPOS HEBDO)',
  RETRR: 'REGLEMENTATION DU TRAVAIL(DUREE, JOURS FERIES,REPOS HEBDO)',
  REVEN: 'REVENDICATION IMMOBILIERE',
  RQREM: "REQUETE EN RECTIFICATION D'ERREURS MATERIELLES",
  RSAVO: 'RESPONSABILITE DES AVOC. OFFIC. PUBL. ET MINIST. CONSE. JUR)',
  RSCON: 'Responsabilité contractuelle',
  RSDEL: 'Responsabilité délictuelle ou quasi délictuelle',
  RSMED: 'RESPONSABILITE MEDICALE (MEDECINS,CHIRURGIENS,CHIR-DENTISTES)',
  SAFER: 'S.A.F.E.R.',
  SALAI: 'SALAIRE ET ACCESSOIRES',
  SALAO: 'SALAIRES ET ACCESSOIRES',
  SALAR: 'SALAIRES ET ACCESSOIRES',
  SARRE: 'SAISIES',
  SECOR: 'Séparation de corps',
  SECU: 'Sécurité sociale',
  SEPOU: 'Séparation des pouvoirs',
  SEPUL: 'Sépulture',
  SEQUE: 'Séquestre',
  SERVI: 'Servitude',
  SIMMO: 'Saisie immobilière',
  SITJO: 'MODIFICATION DE LA SITUATION JURIDIQUE DE L ENTREPRISE',
  SITJR: 'MODIFICATION DE LA SITUATION JURIDIQUE DE L ENTREPRISE',
  SITJU: "MODIFICATION DE LA SITUATION JURIDIQUE DE L'EMPLOYEUR",
  SOAMO: 'ABSENCE DE MOYEN SOMMAIRE',
  SOAMR: 'ABSENCE DE MOYENS SOMMAIRE',
  SOCIM: 'Société civile immobilière',
  SOCIV: 'Société civile',
  SOCOM: 'Société commerciale',
  SOIRO: 'IRRECEVABILITE',
  SOIRR: 'IRRECEVABILITE',
  SUCCE: 'Succession',
  SUSPI: 'Suspicion légitime',
  TARIF: 'Tarifs des officiers publics ou ministériel et avocats postulants',
  TECHN: 'TECHNICIENS DU BATIMENT : RESPONSABILITE',
  TESTA: 'Testament',
  TRANS: 'Transaction',
  TRMAR: 'Transport de marchandises',
  TROVC: 'TROUBLES DE VOISINAGE EN MATIERE DE CONSTRUCTION',
  TROVO: 'Trouble de voisinage',
  TRPER: 'Transport de personnes',
  TXREO: 'TAUX DU RESSORT',
  TXRER: 'TAUX DU RESSORT',
  VCOMM: 'Vente commerciale',
  VEIMM: 'Vente immobilière',
  VEMOB: 'Vente mobilière',
  VISDO: 'Visite et saisie domiciliaires',
  VOIES: "VOIES D'EXECUTION",
  VRP: 'SALARIES A STATUT PARTICULIER (VRP APPRENTIS ARTISTES ETC)',
  VRPO: 'SALARIES A STATUT PARTICULIER VRP APPRENTIS ARTISTES...',
  VRPR: 'SALARIES A STATUT PARTICULIER VRP APPRENTIS ARTISTES...',
  BACOM: 'Bail commercial',
  CACIV: 'Cautionnement civil',
  AGRIC: 'Mutualité sociale agricole',
  AIJUR: 'Aide juridictionnelle',
  ASREG: 'Assurance (règles générales)',
  CREDM: 'Crédit-bail immobilier',
  COTRA: 'Contrat de travaux',
  COCOL: 'Conventions collectives',
  AVOCJ: 'Avocat et conseil juridique',
  AUTSO: 'AUTRES CHAMBRE SOCIALE',
  COTEX: 'Contrat de travail, exécution',
  COTFO: 'Contrat de travail, formation',
  CONTRU: 'CONTRAT DE TRAVAIL, RUPTURE',
  ACC98: 'Accident du travail (Loi de 1898)',
  ALSAL: 'Alsace Lorraine',
  AUTRA: 'Autres droit du travail',
  AUTSS: 'Autres sécurité sociale',
  BREVE: "Brevet d'invention",
  CHOJU: 'Chose jugée',
  COO86: 'Concurrence (Ordonnance du 1er décembre 1986)',
  COO45: 'Concurrence',
  COTRU: 'Contrat de travail, rupture',
  DESMO: 'Dessins et modèles',
  EOHP: 'Elections aux OPHLM (inscription sur les listes)',
  EOHS: 'Elections aux OPHLM (régularité des élections)',
  ECAP: "Elections aux chambres d'agriculture (inscription sur les listes)",
  ECAS: "Elections aux chambres d'agriculture (régularité des élections)",
  ECCP: "Elections aux chambres de commerce et d'industrie (inscription sur les listes)",
  ECCS: "Elections aux chambres de commerce et d'industrie (régularité des élections)",
  ECMS: 'Elections aux chambres des métiers (régularité des élections)',
  ECMP: 'Elections aux chambres des métiers (inscription sur les listes)',
  ECEP: "Elections aux conseils consultatifs des caisses d'épargne et de prévoyance (inscription sur les listes)",
  ECES: "Elections aux conseils consultatifs des caisses d'épargne et de prévoyance (régularité des élections)",
  ECSP: 'Elections aux conseils de la mutualité sociale agricole (inscription sur les listes)',
  ECSS: 'Elections aux conseils de la mutualité sociale agricole (régularité des élections)',
  EPHP: "Elections aux conseils de prud'homme (inscription sur les listes)",
  EPHS: "Elections aux conseils de prud'homme (régularité des élections)",
  ETCP: 'Elections aux tribunaux de commerce (inscription sur les listes)',
  ETCS: 'Elections aux tribunaux de commerce (régularité des inscriptions)',
  EUMP: 'Elections aux unions régionales des médecins exerçant à titre libéral (inscription sur les listes)',
  EUMS: 'Elections aux unions régionales des médecins exerçant à titre libéral (régularité des élections)',
  EFOP: 'Elections forestières (inscription sur les listes)',
  EFOS: 'Elections forestières (régularité des élections)',
  ESCP: 'Elections sécurité sociale (inscription sur les listes)',
  ESCS: 'Elections sécurité sociale (régularité des élections)',
  ENTD2: 'Entreprise en difficulté (loi du 25 janvier 1985)',
  ETRAN: 'Etranger',
  IMPOT: 'Impôts et taxes',
  INVAT: "Indemnisation des victimes d'attentat",
  JEUXH: 'Jeux de hasard',
  MARQU: 'Marque de fabrique',
  NOMCO: 'Nom commercial',
  OPMIN: 'Officiers publics ou ministériels',
  PRCEX: "Procédures civiles  d'exécution",
  PRMED: 'Professions médicales et paramédicales',
  PROPE: 'Protection des droits de la personne',
  PRUDO: "Prud'hommes",
  REPSA: 'Représentation des salariés',
  SOCIP: 'Société civile professionnelle',
  ALSPE: 'Sécurité sociale, aide sociale',
  AVPNN: 'Sécurité sociale, allocation vieillesse pour personnes non-salariées',
  ASSNN: 'Sécurité sociale, assurances sociales des travailleurs indépendants des professions non-agricoles',
  ASSOS: 'Sécurité sociale, assurances sociales du régime général',
  CONTE: 'Sécurité sociale, contentieux',
  PRESF: 'Sécurité sociale, prestations familiales',
  RGCOM: 'Sécurité sociale, régimes complémentaires',
  RGSPE: 'Sécurité sociale, régimes spéciaux et régimes divers',
  TRARG: 'Travail réglementation (travail dissimulé et des étrangers...)',
  AGS: 'AGS',
  APPREN: 'Apprentissage et formation professionnelle',
  ASSED: 'Assedic - chômage',
  CLAUSE: 'Clauses du contrat de travail (Mobilité, non-concurrence, objectifs, variabilité)',
  CONFLI: 'Conflit de juridictions (drt soc.)',
  CONFCO: 'Conflits collectifs du travail  (grève / lock-out...)',
  CONGES: 'Congés payés',
  CTMAND: 'Contrat de travail et mandat social',
  CDD: 'Contrats à durée déterminée',
  CTAIDE: 'Contrats aidés',
  CVEURO: "Convention européenne de sauvegarde des droits de l'homme et des libertés",
  CVCOLI: 'Conventions et accords collectifs : Interprétation et application',
  CVCOLN: 'Conventions et accords collectifs : Négociation et régime',
  DEPART: "Départ de l'entreprise : certificat de travail, reçu pour solde de tout compte",
  DISCRI: 'Discrimination',
  DISCRS: 'Discrimination syndicale',
  DITCIV: 'Droit civil',
  DTCOM: 'Droit commercial (application au droit social du...) et procédures collectives',
  DTDISC: "Droit disciplinaire (règlement intérieur de l'entreprise/amnistie)",
  DTIP: 'Droit international privé (drt soc.)',
  DTLOC: 'Droit local',
  DTMAR: 'Droit maritime du travail - Marins',
  DTPUB: 'Droit public - Droit administratif',
  DTSYND: 'Droit syndical',
  DURAUB: 'Durée du travail : Lois Aubry (ou lois sur les 35 heures)',
  DUREE: 'Durée et temps de travail (astreintes/travail effectif/repos hebdomadaire...)',
  ENTSTA: 'Entreprise à statut spécial : EDF, RATP, SNCF, Air France ...',
  ESSAI: 'Essai (contrat de travail...)',
  ETSANT: 'Etat de santé - Maternité',
  EXIST: 'Existence du contrat de travail',
  HARCEL: 'Harcèlement',
  HYGIEN: 'Hygiène et sécurité',
  IMPUTA: 'Imputabilité de la rupture du contrat de travail',
  IRP: "Institutions représentatives du personnel (comité d'entreprise/délégué du personnel...)",
  IRRECE: 'Irrecevabilités et déchéances',
  LOM: "Législation d'outre-mer",
  LICDIS: 'Licenciement disciplinaire (pour faute)',
  LICECO: 'Licenciement économique collectif',
  LICECI: 'Licenciement économique individuel',
  LICPER: 'Licenciement personnel non disciplinaires',
  MODIFS: "Modification de la situation juridique de l'employeur (L.1224-1 du code du travail)",
  MODIFC: 'Modification du contrat de travail',
  MODIFE: 'Modification du contrat de travail pour motif économique (L.1222-6 du code du travail)',
  REGLE: "Réglementation du travail (non recensée sous d'autres rubriques spécifiques) (2)",
  REMUN: 'Rémunération (salaires et accessoires)',
  RETRAI: 'Retraites',
  RUPTUR: "Rupture négociée du contrat de travail (transaction et rupture d'un commun accord)",
  SCOOP: 'Sociétés coopératives ouvrières de production (S.C.O.(O.)P.)',
  SALSTA:
    'Salariés à statut particulier (artistes, assistantes maternelles, employés de maison, journalistes, gérants non salariés, dockers...)',
  SERVIC: 'Service national',
  SPORT: "Sports-Aviation (contrats de travail conclus dans les sports et l'aviation)",
  STATSA: 'Statut des salariés protégés',
  TINTER: 'Travail intérimaire',
  USAGES: 'Usages et engagements unilatéraux',
  VIPERS: 'Vie personnelle du salarié et libertés individuelles et collectives',
  'V.R.P.': 'V.R.P.',
  PROSOC: "Procédure prud'homale",
  SUREN: 'Surendettement des particuliers et des familles',
  VIPRI: "Atteintes au respect de la vie privée et de la présomption d'innocence",
  ASSCO: 'Assurance construction obligatoire',
  COPAC: 'Concubinage et P.A.C.S.',
  ETAT: 'Etat',
  AGASS: "Agent d'assurance",
  HANDI: 'Handicapé',
  DTEURO: 'Droit européen',
  ETSANM: "Matérnité (congé de maternité, parental d'éducation)",
  CONGET: "Congés - Autres (Création d'entreprise, sabbatique)",
  PARTI: 'Participation des salariés (intéressement)',
  ETSANR: 'Etat de santé - Règles communes',
  ETSAA: 'Etat de santé - Accident du travail et maladie professionnelle',
  ETSAB: 'Etat de santé - Accident et maladie non professionnelle',
  BACONS: 'Bail à construction',
  URBA: 'Urbanisme',
  SAUVE: 'Sauvegarde des entreprises',
  CONDL: 'Concurrence déloyale ou illicite',
  EXPCO: 'Expert-comptable et comptable agréé',
  ENTD3: 'Entreprise en difficulté (loi du 26 juillet 2005)',
  PRESS: 'Presse',
  DONAT: 'Donations',
  ALSMO: 'Alsace Moselle',
  ENVIR: 'Environnement et pollution',
  MANDCO: 'Mandat entre commerçants',
  ETSA: 'Etat de santé (maladie, accident, maternité)',
  FONGA: 'Fonds de garantie',
  CNE: 'Contrat nouvelles embauches',
  EXPRA: 'Expropriation (Arrêt)',
  EXPE2: 'Expert judiciaire (inscription)',
  RSPDEF: 'Responsabilté du fait des produits défectueux',
  MEUBL: 'Meuble',
  OMER: 'Outre-mer',
  CHSCT: "Comité d'hygiène et sécurité : organisation et fonctionnement",
  DRINTD: 'Droit international privé - déplacement illicite',
  AGCOM: 'Agent commercial',
  COMPUB: 'Commandes publiques',
  MED: 'Médiateurs (inscription)',
  APCIV: 'Appel civil',
  JURID: 'Juridictions',
  MESINS: "Mesures d'instruction",
  REQREF: 'Ordonnances sur requête et référé',
  TPAR: 'Temps partiel/Travail intermittent',
  APCOMP: 'Appel - Compétence',
  EXPAT: 'Expatriés - travailleurs détachés',
  FORFAI: 'Forfaits en jours/heures, forfaits de rémunération',
  FRAIPR: 'Frais professionnels',
  JOURN: 'Journalistes/pigistes',
  MEDJU: 'Médiateur judiciaire',
  PORTAG: 'Portage salarial',
  REFERE: "Référé prud'homal",
  SMIC: 'SMIC',
  TRANSP: 'Transports routiers/ambulances',
  AAI: 'Autorités administratives indépendantes (AAI)',
  PRC: 'Pratiques restrictives de concurrence',
  CDIS: 'Contrats de distribution',
  EDIF: 'Entreprise en difficulté',
  PIND: 'Propriété industrielle',
  RESP: "Responsabilité du prestataire de services d'investissement",
  SOCIE: 'Sociétés',
  ASSCC: 'Sécurité sociale, cotisations et contributions du régime général',
  MANDIG: "Mandat d'intérêt général",
  ASSMT: 'Assurances maritimes et transport de marchandises',
  AUTMF: 'Autorité des marchés financiers',
  LOCFI: 'Location financière',
  ENTRS: 'Entreprise en difficulté - Responsabilité et sanctions',
};

const taxon = {};

for (let key in source) {
  let item = source[key].replace(/\s+/gm, ' ');
  item = item.replace(/(\w)\s+\./gm, '$1.');
  item = item.replace(/\(\s+(\w)/gm, '($1');
  item = item.replace(/(\w)\s+\)/gm, '$1)');
  item = item.replace(/(\w)\(/gm, '$1 (');
  item = item.replace(/([^,]),(\w)/gm, '$1, $2');
  item = item.trim();
  if (item && Object.values(taxon).indexOf(item) === -1) {
    taxon[key] = item;
  }
}

module.exports = {
  options: [''].concat(Object.keys(taxon)),
  keys: Object.keys(taxon),
  taxonomy: taxon,
};
