const taxon = {
  1234: "Conseil de prud'hommes d'Abbeville",
  1234: "Conseil de prud'hommes d'Agen",
  1234: "Conseil de prud'hommes d'Aix-en-Provence",
  1234: "Conseil de prud'hommes d'Aix-les-Bains",
  1234: "Conseil de prud'hommes d'Ajaccio",
  1234: "Conseil de prud'hommes d'Albertville",
  1234: "Conseil de prud'hommes d'Albi",
  1234: "Conseil de prud'hommes d'Alençon",
  1234: "Conseil de prud'hommes d'Alès",
  1234: "Conseil de prud'hommes d'Amiens",
  1234: "Conseil de prud'hommes d'Angers",
  1234: "Conseil de prud'hommes d'Angoulême",
  1234: "Conseil de prud'hommes d'Annecy",
  1234: "Conseil de prud'hommes d'Annemasse",
  1234: "Conseil de prud'hommes d'Annonay",
  1234: "Conseil de prud'hommes d'Argentan",
  1234: "Conseil de prud'hommes d'Argenteuil",
  1234: "Conseil de prud'hommes d'Arles",
  1234: "Conseil de prud'hommes d'Arras",
  1234: "Conseil de prud'hommes d'Aubenas",
  1234: "Conseil de prud'hommes d'Auch",
  1234: "Conseil de prud'hommes d'Aurillac",
  1234: "Conseil de prud'hommes d'Auxerre",
  1234: "Conseil de prud'hommes d'Avesnes-sur-Helpe",
  1234: "Conseil de prud'hommes d'Avignon",
  1234: "Conseil de prud'hommes d'Avranches",
  1234: "Conseil de prud'hommes de Bar-le-Duc",
  1234: "Conseil de prud'hommes de Basse-Terre",
  1234: "Conseil de prud'hommes de Bastia",
  1234: "Conseil de prud'hommes de Bayonne",
  1234: "Conseil de prud'hommes de Beauvais",
  1234: "Conseil de prud'hommes de Belfort",
  1234: "Conseil de prud'hommes de Belley",
  1234: "Conseil de prud'hommes de Bergerac",
  1234: "Conseil de prud'hommes de Bernay",
  1234: "Conseil de prud'hommes de Besançon",
  1234: "Conseil de prud'hommes de Blois",
  1234: "Conseil de prud'hommes de Bobigny",
  1234: "Conseil de prud'hommes de Bonneville",
  1234: "Conseil de prud'hommes de Bordeaux",
  1234: "Conseil de prud'hommes de Boulogne-Billancourt",
  1234: "Conseil de prud'hommes de Boulogne-sur-Mer",
  1234: "Conseil de prud'hommes de Bourg-en-Bresse",
  1234: "Conseil de prud'hommes de Bourges",
  1234: "Conseil de prud'hommes de Bourgoin-Jallieu",
  1234: "Conseil de prud'hommes de Brest",
  1234: "Conseil de prud'hommes de Brive-la-Gaillarde",
  1234: "Conseil de prud'hommes de Béthune",
  1234: "Conseil de prud'hommes de Béziers",
  1234: "Conseil de prud'hommes de Caen",
  1234: "Conseil de prud'hommes de Cahors",
  1234: "Conseil de prud'hommes de Calais",
  1234: "Conseil de prud'hommes de Cambrai",
  1234: "Conseil de prud'hommes de Cannes",
  1234: "Conseil de prud'hommes de Carcassonne",
  1234: "Conseil de prud'hommes de Castres",
  1234: "Conseil de prud'hommes de Cayenne",
  1234: "Conseil de prud'hommes de Cergy-Pontoise",
  1234: "Conseil de prud'hommes de Chalon-sur-Saône",
  1234: "Conseil de prud'hommes de Chambéry",
  1234: "Conseil de prud'hommes de Charleville-Mézières",
  1234: "Conseil de prud'hommes de Chartres",
  1234: "Conseil de prud'hommes de Chaumont",
  1234: "Conseil de prud'hommes de Cherbourg-en-Cotentin",
  1234: "Conseil de prud'hommes de Châlons-en-Champagne",
  1234: "Conseil de prud'hommes de Châteaudun",
  1234: "Conseil de prud'hommes de Châteauroux",
  1234: "Conseil de prud'hommes de Clermont-Ferrand",
  1234: "Conseil de prud'hommes de Colmar",
  1234: "Conseil de prud'hommes de Compiègne",
  1234: "Conseil de prud'hommes de Coutances",
  1234: "Conseil de prud'hommes de Creil",
  1234: "Conseil de prud'hommes de Créteil",
  1234: "Conseil de prud'hommes de Dax",
  1234: "Conseil de prud'hommes de Dieppe",
  1234: "Conseil de prud'hommes de Digne-les-Bains",
  1234: "Conseil de prud'hommes de Dijon",
  1234: "Conseil de prud'hommes de Dinan",
  1234: "Conseil de prud'hommes de Dole",
  1234: "Conseil de prud'hommes de Douai",
  1234: "Conseil de prud'hommes de Draguignan",
  1234: "Conseil de prud'hommes de Dreux",
  1234: "Conseil de prud'hommes de Dunkerque",
  1234: "Conseil de prud'hommes d'Épernay",
  1234: "Conseil de prud'hommes d'Épinal",
  1234: "Conseil de prud'hommes d'Évreux",
  1234: "Conseil de prud'hommes de Foix",
  1234: "Conseil de prud'hommes de Fontainebleau",
  1234: "Conseil de prud'hommes de Forbach",
  1234: "Conseil de prud'hommes de Fort-de-France",
  1234: "Conseil de prud'hommes de Fréjus",
  1234: "Conseil de prud'hommes de Gap",
  1234: "Conseil de prud'hommes de Grasse",
  1234: "Conseil de prud'hommes de Grenoble",
  1234: "Conseil de prud'hommes de Guingamp",
  1234: "Conseil de prud'hommes de Guéret",
  1234: "Conseil de prud'hommes d'Haguenau",
  1234: "Conseil de prud'hommes du Havre",
  1234: "Conseil de prud'hommes d'Hazebrouck",
  1234: "Conseil de prud'hommes de Laon",
  1234: "Conseil de prud'hommes de Laval",
  1234: "Conseil de prud'hommes de Lens",
  1234: "Conseil de prud'hommes de Libourne",
  1234: "Conseil de prud'hommes de Lille",
  1234: "Conseil de prud'hommes de Limoges",
  1234: "Conseil de prud'hommes de Lisieux",
  1234: "Conseil de prud'hommes de Longjumeau",
  1234: "Conseil de prud'hommes de Longwy",
  1234: "Conseil de prud'hommes de Lons-le-Saunier",
  1234: "Conseil de prud'hommes de Lorient",
  1234: "Conseil de prud'hommes de Louviers",
  1234: "Conseil de prud'hommes de Lure",
  1234: "Conseil de prud'hommes de Lyon",
  1234: "Conseil de prud'hommes de Lys-Lez-Lannoy",
  1234: "Conseil de prud'hommes de Mamoudzou",
  1234: "Conseil de prud'hommes du Mans",
  1234: "Conseil de prud'hommes de Mantes-la-Jolie",
  1234: "Conseil de prud'hommes de Marmande",
  1234: "Conseil de prud'hommes de Marseille",
  1234: "Conseil de prud'hommes de Martigues",
  1234: "Conseil de prud'hommes de Meaux",
  1234: "Conseil de prud'hommes de Melun",
  1234: "Conseil de prud'hommes de Mende",
  1234: "Conseil de prud'hommes de Metz",
  1234: "Conseil de prud'hommes de Millau",
  1234: "Conseil de prud'hommes de Montargis",
  1234: "Conseil de prud'hommes de Montauban",
  1234: "Conseil de prud'hommes de Montbrison",
  1234: "Conseil de prud'hommes de Montbéliard",
  1234: "Conseil de prud'hommes de Mont-de-Marsan",
  1234: "Conseil de prud'hommes de Montluçon",
  1234: "Conseil de prud'hommes de Montmorency",
  1234: "Conseil de prud'hommes de Montpellier",
  1234: "Conseil de prud'hommes de Montélimar",
  1234: "Conseil de prud'hommes de Morlaix",
  1234: "Conseil de prud'hommes de Moulins",
  1234: "Conseil de prud'hommes de Mulhouse",
  1234: "Conseil de prud'hommes de Mâcon",
  1234: "Conseil de prud'hommes de Nancy",
  1234: "Conseil de prud'hommes de Nanterre",
  1234: "Conseil de prud'hommes de Nantes",
  1234: "Conseil de prud'hommes de Narbonne",
  1234: "Conseil de prud'hommes de Nevers",
  1234: "Conseil de prud'hommes de Nice",
  1234: "Conseil de prud'hommes de Niort",
  1234: "Conseil de prud'hommes de Nîmes",
  1234: "Conseil de prud'hommes d'Orange",
  1234: "Conseil de prud'hommes d'Orléans",
  1234: "Conseil de prud'hommes d'Oyonnax",
  1234: "Conseil de prud'hommes de Paris",
  1234: "Conseil de prud'hommes de Pau",
  1234: "Conseil de prud'hommes de Perpignan",
  1234: "Conseil de prud'hommes de Pointe-à-Pitre",
  1234: "Conseil de prud'hommes de Poissy",
  1234: "Conseil de prud'hommes de Poitiers",
  1234: "Conseil de prud'hommes du Puy-en-Velay",
  1234: "Conseil de prud'hommes de Périgueux",
  1234: "Conseil de prud'hommes de Péronne",
  1234: "Conseil de prud'hommes de Quimper",
  1234: "Conseil de prud'hommes de Rambouillet",
  1234: "Conseil de prud'hommes de Reims",
  1234: "Conseil de prud'hommes de Rennes",
  1234: "Conseil de prud'hommes de Riom",
  1234: "Conseil de prud'hommes de Roanne",
  1234: "Conseil de prud'hommes de Rochefort",
  1234: "Conseil de prud'hommes de La Rochelle",
  1234: "Conseil de prud'hommes de La Roche-sur-Yon",
  1234: "Conseil de prud'hommes de Rodez",
  1234: "Conseil de prud'hommes de Roubaix",
  1234: "Conseil de prud'hommes de Rouen",
  1234: "Conseil de prud'hommes des Sables d'Olonne",
  1234: "Conseil de prud'hommes de Saint-Brieuc",
  1234: "Conseil de prud'hommes de Saint-Denis",
  1234: "Conseil de prud'hommes de Saint-Dié-des-Vosges",
  1234: "Conseil de prud'hommes de Saintes",
  1234: "Conseil de prud'hommes de Saint-Étienne",
  1234: "Conseil de prud'hommes de Saint-Gaudens",
  1234: "Conseil de prud'hommes de Saint-Germain-en-Laye",
  1234: "Conseil de prud'hommes de Saint-Malo",
  1234: "Conseil de prud'hommes de Saint-Nazaire",
  1234: "Conseil de prud'hommes de Saint-Omer",
  1234: "Conseil de prud'hommes de Saint-Pierre",
  1234: "Conseil de prud'hommes de Saint-Quentin",
  1234: "Conseil de prud'hommes de Saumur",
  1234: "Conseil de prud'hommes de Saverne",
  1234: "Conseil de prud'hommes de Schiltigheim",
  1234: "Conseil de prud'hommes de Sens",
  1234: "Conseil de prud'hommes de Soissons",
  1234: "Conseil de prud'hommes de St-Pierre-et-Miquelon",
  1234: "Conseil de prud'hommes de Strasbourg",
  1234: "Conseil de prud'hommes de Sète",
  1234: "Conseil de prud'hommes de Tarbes",
  1234: "Conseil de prud'hommes de Thionville",
  1234: "Conseil de prud'hommes de Thouars",
  1234: "Conseil de prud'hommes de Toulon",
  1234: "Conseil de prud'hommes de Toulouse",
  1234: "Conseil de prud'hommes de Tourcoing",
  1234: "Conseil de prud'hommes de Tours",
  1234: "Conseil de prud'hommes de Troyes",
  1234: "Conseil de prud'hommes de Tulle",
  1234: "Conseil de prud'hommes de Valence",
  1234: "Conseil de prud'hommes de Valenciennes",
  1234: "Conseil de prud'hommes de Vannes",
  1234: "Conseil de prud'hommes de Verdun",
  1234: "Conseil de prud'hommes de Versailles",
  1234: "Conseil de prud'hommes de Vesoul",
  1234: "Conseil de prud'hommes de Vichy",
  1234: "Conseil de prud'hommes de Vienne",
  1234: "Conseil de prud'hommes de Villefranche-sur-Saône",
  1234: "Conseil de prud'hommes de Villeneuve-Saint-Georges",
  1234: "Conseil de prud'hommes d'Évry-Courcouronnes",
  1234: 'Tribunal du travail de Mata-Utu',
  1234: 'Tribunal du travail de Nouméa',
  1234: 'Tribunal du travail de Nuku-Hiva',
  1234: 'Tribunal du travail de Papeete',
  1234: 'Tribunal du travail de Raïatéa',
};

module.exports = {
  options: [''].concat(Object.keys(taxon)),
  keys: Object.keys(taxon),
  taxonomy: taxon,
};
