const taxon = {
  4701: "Conseil de prud'hommes d'Agen",
  1301: "Conseil de prud'hommes d'Aix-en-Provence",
  2001: "Conseil de prud'hommes d'Ajaccio",
  8101: "Conseil de prud'hommes d'Albi",
  6101: "Conseil de prud'hommes d'Alençon",
  8002: "Conseil de prud'hommes d'Amiens",
  4901: "Conseil de prud'hommes d'Angers",
  1601: "Conseil de prud'hommes d'Angoulême",
  7401: "Conseil de prud'hommes d'Annecy",
  '0601': "Conseil de prud'hommes d'Antibes",
  6201: "Conseil de prud'hommes d'Arras",
  '0702': "Conseil de prud'hommes d'Aubenas",
  3201: "Conseil de prud'hommes d'Auch",
  1501: "Conseil de prud'hommes d'Aurillac",
  8901: "Conseil de prud'hommes d'Auxerre",
  8401: "Conseil de prud'hommes d'Avignon",
  5501: "Conseil de prud'hommes de Bar-le-Duc",
  9711: "Conseil de prud'hommes de Basse-Terre",
  2002: "Conseil de prud'hommes de Bastia",
  6401: "Conseil de prud'hommes de Bayonne",
  6001: "Conseil de prud'hommes de Beauvais",
  9001: "Conseil de prud'hommes de Belfort",
  2401: "Conseil de prud'hommes de Bergerac",
  2701: "Conseil de prud'hommes de Bernay",
  2501: "Conseil de prud'hommes de Besançon",
  3402: "Conseil de prud'hommes de Béziers",
  4101: "Conseil de prud'hommes de Blois",
  9301: "Conseil de prud'hommes de Bobigny",
  3302: "Conseil de prud'hommes de Bordeaux",
  6202: "Conseil de prud'hommes de Boulogne-sur-Mer",
  '0101': "Conseil de prud'hommes de Bourg-en-Bresse",
  1801: "Conseil de prud'hommes de Bourges",
  2901: "Conseil de prud'hommes de Brest",
  5401: "Conseil de prud'hommes de Briey",
  1901: "Conseil de prud'hommes de Brive-la-Gaillarde",
  1402: "Conseil de prud'hommes de Caen",
  4601: "Conseil de prud'hommes de Cahors",
  '0602': "Conseil de prud'hommes de Cannes",
  1101: "Conseil de prud'hommes de Carcassonne",
  8102: "Conseil de prud'hommes de Castres",
  9731: "Conseil de prud'hommes de Cayenne",
  7102: "Conseil de prud'hommes de Chalon-sur-Saône",
  5101: "Conseil de prud'hommes de Chalons-en-Champagne",
  7301: "Conseil de prud'hommes de Chambéry",
  2801: "Conseil de prud'hommes de Chartres",
  3601: "Conseil de prud'hommes de Châteauroux",
  5201: "Conseil de prud'hommes de Chaumont",
  5001: "Conseil de prud'hommes de Cherbourg",
  6303: "Conseil de prud'hommes de Clermont-Ferrand",
  6002: "Conseil de prud'hommes de Compiègne",
  5002: "Conseil de prud'hommes de Coutances",
  9401: "Conseil de prud'hommes de Créteil",
  '0301': "Conseil de prud'hommes de Cusset",
  4001: "Conseil de prud'hommes de Dax",
  7601: "Conseil de prud'hommes de Dieppe",
  2104: "Conseil de prud'hommes de Dijon",
  5952: "Conseil de prud'hommes de Douai",
  8302: "Conseil de prud'hommes de Draguignan",
  5902: "Conseil de prud'hommes de Dunkerque",
  8801: "Conseil de prud'hommes d'Épinal",
  2702: "Conseil de prud'hommes d'Évreux",
  7801: "Conseil de prud'hommes d'Évry",
  '0901': "Conseil de prud'hommes de Foix",
  9721: "Conseil de prud'hommes de Fort-de-France",
  8303: "Conseil de prud'hommes de Fréjus",
  '0501': "Conseil de prud'hommes de Gap",
  '0603': "Conseil de prud'hommes de Grasse",
  3801: "Conseil de prud'hommes de Grenoble",
  2301: "Conseil de prud'hommes de Guéret",
  8501: "Conseil de prud'hommes de La Roche-sur-Yon",
  1704: "Conseil de prud'hommes de La Rochelle",
  5301: "Conseil de prud'hommes de Laval",
  7606: "Conseil de prud'hommes du Havre",
  7202: "Conseil de prud'hommes du Mans",
  4302: "Conseil de prud'hommes du Puy-en-Velay",
  3303: "Conseil de prud'hommes de Libourne",
  5910: "Conseil de prud'hommes de Lille Métropole",
  8701: "Conseil de prud'hommes de Limoges",
  1407: "Conseil de prud'hommes de Lisieux",
  3902: "Conseil de prud'hommes de Lons-le-Saunier",
  5601: "Conseil de prud'hommes de Lorient",
  6901: "Conseil de prud'hommes de Lyon",
  7106: "Conseil de prud'hommes de Mâcon",
  9761: "Conseil de prud'hommes de Mamoudzou",
  '0401': "Conseil de prud'hommes de Manosque",
  1303: "Conseil de prud'hommes de Marseille",
  7701: "Conseil de prud'hommes de Meaux",
  7702: "Conseil de prud'hommes de Melun",
  4801: "Conseil de prud'hommes de Mende",
  4002: "Conseil de prud'hommes de Mont-de-Marsan",
  8201: "Conseil de prud'hommes de Montauban",
  '0303': "Conseil de prud'hommes de Montluçon",
  3405: "Conseil de prud'hommes de Montpellier",
  5402: "Conseil de prud'hommes de Nancy",
  9201: "Conseil de prud'hommes de Nanterre",
  4401: "Conseil de prud'hommes de Nantes",
  1104: "Conseil de prud'hommes de Narbonne",
  5802: "Conseil de prud'hommes de Nevers",
  '0605': "Conseil de prud'hommes de Nice",
  3003: "Conseil de prud'hommes de Nîmes",
  7901: "Conseil de prud'hommes de Niort",
  4502: "Conseil de prud'hommes d'Orléans",
  7501: "Conseil de prud'hommes de Paris",
  6403: "Conseil de prud'hommes de Pau",
  2402: "Conseil de prud'hommes de Périgueux",
  6601: "Conseil de prud'hommes de Perpignan",
  9712: "Conseil de prud'hommes de Pointe-à-Pitre",
  8602: "Conseil de prud'hommes de Poitiers",
  7802: "Conseil de prud'hommes de Pontoise",
  2903: "Conseil de prud'hommes de Quimper",
  5103: "Conseil de prud'hommes de Reims",
  3501: "Conseil de prud'hommes de Rennes",
  4201: "Conseil de prud'hommes de Roanne",
  1203: "Conseil de prud'hommes de Rodez",
  2602: "Conseil de prud'hommes de Romans",
  7608: "Conseil de prud'hommes de Rouen",
  2202: "Conseil de prud'hommes de Saint-Brieuc",
  9741: "Conseil de prud'hommes de Saint-Denis de La Réunion",
  4202: "Conseil de prud'hommes de Saint-Etienne",
  3502: "Conseil de prud'hommes de Saint-Malo",
  4402: "Conseil de prud'hommes de Saint-Nazaire",
  9742: "Conseil de prud'hommes de Saint-Pierre de La Réunion",
  '0202': "Conseil de prud'hommes de Saint-Quentin",
  1708: "Conseil de prud'hommes de Saintes",
  1304: "Conseil de prud'hommes de Salon-de-Provence",
  '0802': "Conseil de prud'hommes de Sedan",
  8903: "Conseil de prud'hommes de Sens",
  '0203': "Conseil de prud'hommes de Soissons",
  1305: "Conseil de prud'hommes de Tarascon",
  6502: "Conseil de prud'hommes de Tarbes",
  7402: "Conseil de prud'hommes de Thonon-les-Bains",
  8305: "Conseil de prud'hommes de Toulon",
  3102: "Conseil de prud'hommes de Toulouse",
  3701: "Conseil de prud'hommes de Tours",
  1001: "Conseil de prud'hommes de Troyes",
  5906: "Conseil de prud'hommes de Valenciennes",
  5602: "Conseil de prud'hommes de Vannes",
  7001: "Conseil de prud'hommes de Vesoul - Gray",
  7803: "Conseil de prud'hommes de Versailles",
  3802: "Conseil de prud'hommes de Vienne",
  6903: "Conseil de prud'hommes de Villefranche-sur-Saône - Tarare",
};

module.exports = {
  options: [''].concat(Object.keys(taxon)),
  keys: Object.keys(taxon),
  taxonomy: taxon,
};
